name: Release a new version
on:
  push:
    branches:
    - refs/tags/*

jobs:
  faster:
    name: Create a release from tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Dump GitHub context
      run: echo "${{ toJson(github) }}"

#    - name: All
#      run: docker build -t test --file Dockerfile .
#    - name: Save all
#      run: >
#        mkdir -p out/ &&
#        docker images test --format "{{.Repository}}:{{.Tag}}" | xargs -I% sh -c "docker save % | gzip > out/%.tgz" &&
#        for file in $(ls out/); do
#          mv out/${file} out/$(echo ${file} | tr : -)
#        done
#    - name: Upload
#      uses: actions/upload-artifact@master
#      with:
#        name: containers
#        path: out/

#    - name: own action
#      uses: meeDamian/sync-readme@v1.0.0
#      with:
#        user: ${{ secrets.DOCKER_USER }}
#        pass: ${{ secrets.DOCKER_PASS }}
#        slug: ${{ github.repository }}

