name: Create shortened tags

# Only triggered on git tag push
on:
  push:
    tags: [ 'v*' ]

jobs:
  shorten:
    name: Short tags
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set environment
        run: echo "::set-env name=TAG::${GITHUB_REF#refs/tags/}"

      - name: Create, or update the short-name branch
        if: startsWith(env.TAG, 'v0.0') != true
        run: |
          SHORT="$(echo "${TAG#v}" | cut -d. -f-2)"

          echo "$TAG | $SHORT"
