name: build

on:
  push:
    tags: [ '*' ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    env:
      VERSION: v9.9.9

    steps:
      - uses: actions/checkout@v2

      - name: Create some fake archive
        run: tar -czvf aaa.tgz aaa/

      - name: Create Complete Github Release
        uses: meeDamian/github-release@release-v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.VERSION }}
          gzip: false
          files: >
            aaa_bbb.txt:aaa/bbb
            aaa.tgz
