name: build

on: [ push ]
#  push:
#    tags: [ '*' ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    env:
      VERSION: v10.10.10

    steps:
      - uses: actions/checkout@v2

      - name: Create some fake archive
        run: tar -czvf aaa.tgz aaa/

      - name: Create Complete Github Release
        uses: meeDamian/github-release@variables
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.VERSION }}
          name: Can 'U' even "imagine" "quotes" in name!?
          allow_override: true
          body: |
            Everythinger.
            Something that's "very" quoted.
            Absolutely eve"ryt"hing ${{ env.VERSION }}.
            https://docs.github.com/en/rest

            \\\\\\\\\\\\\ //////////\/\/\/\/\/\/
          files: >
            aaa_bbb.txt:aaa/bbb
            aaa.tgz
