name: build

on: [ push ]
#  push:
#    tags: [ '*' ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    env:
      VERSION: v9.9.9

    steps:
      - uses: actions/checkout@v2

      - name: Create some fake archive
        run: tar -czvf aaa.tgz aaa/

      - name: Create Complete Github Release
        uses: meeDamian/github-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          gzip: false
          body: |
            Everything.

            Absolutely everything ${{ env.VERSION }}.
          files: >
            aaa_bbb.txt:aaa/bbb
            aaa.tgz
